# Generated by Django 6.0 on 2026-01-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory_usersession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=50),
        ),
    ]
