# Generated by Django 6.0 on 2025-12-31 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='worker_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('total_tasks', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_tracking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='workers.worker')),
            ],
            options={
                'db_table': 'worker_location',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['worker_id', '-recorded_at'], name='worker_loca_worker__5caf26_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkerMonthlyStats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('resolved_tasks', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('badge', models.CharField(choices=[('None', 'None'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='None', max_length=20)),
                ('monthly_rank', models.IntegerField(blank=True, null=True)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='workers.worker')),
            ],
            options={
                'db_table': 'workers_worker_monthly_stats',
                'ordering': ['-month'],
                'unique_together': {('worker_id', 'month')},
            },
        ),
    ]
