# Generated by Django 6.0 on 2025-12-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Worker', 'Worker'), ('Admin', 'Admin')], max_length=20)),
                ('actor_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
