# Generated by Django 6.0 on 2025-12-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('metric_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_reports', models.IntegerField(default=0)),
                ('pending_reports', models.IntegerField(default=0)),
                ('resolved_reports', models.IntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(default=0.0)),
                ('active_citizens', models.IntegerField(default=0)),
                ('active_workers', models.IntegerField(default=0)),
                ('new_registrations', models.IntegerField(default=0)),
                ('system_uptime', models.FloatField(default=100.0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('ai_accuracy', models.FloatField(default=0.0)),
                ('ai_verifications', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserMonthlyStats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.CharField(max_length=7)),
                ('verified_reports', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_monthly_stats',
            },
        ),
        migrations.CreateModel(
            name='WorkerMonthlyStats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.CharField(max_length=7)),
                ('resolved_tasks', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_worker_monthly_stats',
            },
        ),
    ]
