# Generated by Django 6.0 on 2025-12-31 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('ai_result', models.CharField(choices=[('Unverified', 'Unverified'), ('Waste', 'Waste'), ('No Waste', 'No Waste')], default='Unverified', max_length=20)),
                ('waste_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=8, max_digits=11, null=True)),
                ('image_before', models.CharField(max_length=512)),
                ('image_after', models.CharField(blank=True, max_length=512, null=True)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('citizen_id', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('worker_id', models.ForeignKey(blank=True, db_column='worker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='reports_status_590649_idx'), models.Index(fields=['citizen_id', '-submitted_at'], name='reports_citizen_bf530e_idx'), models.Index(fields=['worker_id', '-submitted_at'], name='reports_worker__f6ffa9_idx')],
            },
        ),
    ]
