# Generated by Django 6.0 on 2026-01-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_after',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='reports/after/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_before',
            field=models.ImageField(max_length=512, upload_to='reports/before/'),
        ),
    ]
