# Generated by Django 6.0 on 2026-01-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_image_after_alter_report_image_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
