# Generated by Django 6.0 on 2026-01-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
