# Generated by Django 6.0 on 2025-12-31 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Worker', 'Worker'), ('Admin', 'Admin')], max_length=10)),
                ('recipient_id', models.IntegerField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncQueue',
            fields=[
                ('sync_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('citizen_id', models.IntegerField()),
                ('payload_json', models.JSONField()),
                ('sync_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offline_sync_queue',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
