# Generated by Django 6.0 on 2026-01-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfflineSyncQueue',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
